### ISSUE TITLE
Issue with upper restarts in python code for stretched grid

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOS_Util#13]
If we run stretched grid case, we get NAN's in some of the restart files. A month ago some [code](https://github.com/GEOS-ESM/GEOS_Util/blame/main/pre/remap_restart/remap_upper.py) was added to address this but seems like it is not woking as intended. 
Also to run this option, this new grid has to be added.  

I was testing 2160 case and gocart for example looks like this:
<img width="804" alt="Screenshot 2023-04-24 at 9 16 20 AM" src="https://user-images.githubusercontent.com/68251545/234007668-3e9bce83-0a12-4c38-b2b5-ec130a142912.png">

@mathomp4 @weiyuan-jiang  @atrayano

**Comment by biljanaorescanin** [comment]
PR https://github.com/GEOS-ESM/GEOS_Util/pull/14 is addressing this issue.

**Comment by mathomp4** [comment]
#14 was merged. Closing.
