### ISSUE TITLE
remap_upper.py should pass in stretch factors to interp_restarts

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOS_Util#15]
After talking with @bena-nasa, the right way to pass in stretch grid factors in `remap_upper.py` is to do so through command line arguments to `interp_restarts.x`. 

If you do it this way, the restarts get global metadata for the stretch factor, lon, and lat.

**Comment by mathomp4** [comment]
Oh dear. I tried this and for some reason the winds (and other things) are *very* different when you a namelist vs options. 

@bena-nasa is looking at this.

**Comment by gmao-rreichle** [comment]
Addressed in #19
