### ISSUE TITLE
move remap_restart from ./post to ./pre and update CODEOWNERS

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOS_Util#2]
@mathomp4, when you get a chance:

1) Please move `./post/remap_restart` to .`/pre` (see https://github.com/GEOS-ESM/GEOSldas/pull/623 for discussion).

2) Make sure the land team or at least @weiyuan-jiang will be informed of future changes in remap_restart via the [CODEOWNERS](https://github.com/GEOS-ESM/GEOS_Util/blob/e3714c4fbf5dbff8b42364d4217d595df2350dd1/.github/CODEOWNERS#L18) mechanism.  There are two teams of interest: @GEOS-ESM/preprocessing-team and @GEOS-ESM/surface-preproc-team 
Neither of these teams includes @weiyuan-jiang.  He's the primary author of the python code in `remap_restart`.

cc: @sdrabenh @biljanaorescanin

**Comment by mathomp4** [comment]
@gmao-rreichle Should we move `regrid.pl` at the same time? I mean they are roughly the same thing.

**Comment by sdrabenh** [comment]
I would suggest moving `regrid.pl` into the `pre` directory as well so the two tools live side-by-side for now. Again, nobody should be running these from the `src` directory, so maybe it is a good thing if they can't find them in `post`. I think the individuals that would be editing these scripts will likely know they have moved. I'm happy to field any questions regarding their whereabouts.
