### ISSUE TITLE
Preconvert Binary Merra2 to NetCDF before conversion

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOS_Util#20]
Matt found that Bill reorder the AddInternalSpec calls in Moist. This is a problem if you use MERRA2 restarts since the binary restarts only work if you add the internal specs in the SAME order as the binary restarts have them so Matt had to reorder them so that this was true. This is clearly stupid and untenable in the long run as the components are refactored.

There is a very simple solution. I already have a script there that given the right input files (which I have there) that describe the contents of the binary files converts them to NetCDF. The regridding script needs simply convert the MERRA2 restarts to NetCDF before converting them.

https://github.com/bena-nasa/GEOS5_restart_converter/tree/master

I'm pretty sure this is broken for Python3 so I will clean this up.

**Comment by biljanaorescanin** [comment]
This has been addressed in #19
