### ISSUE TITLE
Binary to netCDF MERRA-2 converter is broken

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/GEOS_Util#41]
The converter has hardcoded yaml configuration that correspond to the MERRA-2 horizontal and vertical setup. This work great (thanks Ben!) as long as you are not regridding MERRA-2 with resolution change, especially vertical. When I tried to use 'remap_restarts.py' going from MERRA-2 to c720, L137, the netCDF output was badly broken (AK, BK had NaN) and some of the metadata was still pointing to 72/73 levels. My particular workaround was to edit my copies of bin2nc_merra*.yaml files prior to running remap_restarts.pl.

**Comment by gmao-rreichle** [comment]
Presumably addressed in #44
