### ISSUE TITLE
remap_restarts.py needs -constraint option

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/GEOS_Util#46]
In order to run on Milan nodes at NCCS from command line we need to include a -constraint option. So the scripts can include --constraint=mil

We may want to check the logic of -partition as well, I used this on command line -partition scutest but the yaml still includes compute. And I get an error:

cd /gpfsm/dnb03/projects/p38/Ops12KM_R/GMAO_PROPOSAL_BENCHMARK_SETUPS/restarts_x0048_e20211130_21z_c360_L91
use Config yaml file: /discover/nobackup/projects/gmao/osse2/Ops12KM_R/GMAO_PROPOSAL_BENCHMARK_SETUPS/restarts_x0048_e20211130_21z_c360_L91/remap_params.yaml
-partition: Command not found.

Also, I often struggle with having to provide a QOS, debug is restrictive of time, and allnccs doesn't seem to work for me all the time, not sure why.

**Comment by mathomp4** [comment]
@wmputman Note: I believe @weiyuan-jiang is looking now to make `remap_restarts.py` aware of the Milans. But that means we have to do the same "only allow Milan when built on SLES15" business we do elsewhere.

But this should also be done when we fix that up.

**Comment by wmputman** [comment]
OK, I just made my own local modification to get it to work in my scripts
