### ISSUE TITLE
v2.0.4 (which is used by GEOSgcm fixture v11.4.0) fails when regridding merra2 to something other than 72 levels with remap_restarts.py

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOS_Util#48]
A user reported that with the v11.4.0 of the GEOSgcm fixture (which uses v2.0.4 of GEOS_Util) they were getting error when regridding merra2 restarts to something other than 72 levels with remap_restarts.py.
I was able to reproduce this. The upper air regridding just fails with all kinds of errors like this and you don't get the upper air restarts when I try to regrid merra2 restart to 181 levels:
```
 PSDRY_NEW:   983.04999893441      PSDRY_OLD:   983.04206525962      RATIO:   1.00000807053438368      DIF:  0.79336747883644E-02
 PSDRY_NEW:   983.04999893441      PSDRY_OLD:   983.04999893441      RATIO:   1.00000000000000000      DIF:   0.0000000000000
 Updating FV3 NonHydrostatic State
 Writing : fvcore_internal_rst_c0090_181L
pe=00000 FAIL at line=00037    NetCDF4_put_var.H                        <status=-57>
 MAPL_VarWriteNCpar_R8_1dError writing variable          -57
 NetCDF: Start+count exceeds dimension bound

pe=00000 FAIL at line=01735    NCIO.F90                                 <status=-57>
pe=00000 FAIL at line=00037    NetCDF4_put_var.H                        <status=-57>
 MAPL_VarWriteNCpar_R8_1dError writing variable          -57
 NetCDF: Start+count exceeds dimension bound

pe=00000 FAIL at line=01735    NCIO.F90                                 <status=-57>
 Writing : fvcore_internal_rst_c0090_181L U
 Global Area=   510064471910264.
 U      115.8030      -107.6895      0.1908877
 Writing : fvcore_internal_rst_c0090_181L V
 V      123.6169      -159.9293     -0.6733837
 Writing : fvcore_internal_rst_c0090_181L PT
 T      307.9005       162.3629       285.4557
 Writing : fvcore_internal_rst_c0090_181L PE
pe=00000 FAIL at line=00037    NetCDF4_put_var.H                        <status=-40>
```
Now I believe this is not interp_restarts.x, but rather something about the remap_restarts.py or other code in the GEOS_Util repo because if I update to this branch
feature/wjiang/add_ease_grid
which I had originally done because @weiyuan-jiang it was milan node aware, I'm able to regrid all the upper air restarts. So clearly it is not the actual fortran code but something about how it is executed but he python scripting.

So seems like clearly something have been fixed and you probably need to make a new release sooner rather than later that @sdrabenh  can use in a new fixture release. If there is stuff in this branch that is not ready for prime time, then we need to figurewhat has changed that fixed this and perhaps get just that in a new release.

**Comment by biljanaorescanin** [comment]
Yes, that was a problem and it was fixed with this PR: https://github.com/GEOS-ESM/GEOS_Util/pull/44 we had release with fix https://github.com/GEOS-ESM/GEOS_Util/releases/tag/v2.0.5
