### ISSUE TITLE
Minor questionary oddity in remap_restarts

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOS_Util#67]
In testing `remap_restarts.py` today I saw when running the questionary:

```
? ('Select/enter SLURM or PBS account:\n',) g0620
? ('Enter SLURM or PBS partition: (If desired; can leave blank.)\n',)
```
It's like raw strings somehow got in there? Not sure how to fix, but I thought I'd ping @weiyuan-jiang 

None of the other questions seem to look like this.

Also, I'll mention @sshakoor1 in case he's seen this with his gcm_setup work.

**Comment by weiyuan-jiang** [comment]
What is the issue here ? @mathomp4

**Comment by mathomp4** [comment]
Well, it's just a question of style. Most of the questionary questions look like:
```
? Remap upper air restarts? Yes
? Remap agcm_import_rst (a.k.a. IAU) file needed for REPLAY runs?
                        (NOTE: Preferred method is to regenerate IAU file,
                               but IF requested, remapping will be performed.) No
? Remap surface restarts? Yes
? Remap bkg files?  (Required by ADAS but not mapped onto ADAS grid; run one ADAS cycle to spin up.)  No
? Write lcv file?  (Required by ADAS.)  No
```

Whereas these two have parentheses around them, quotes, and a `\n` as well:

```
? ('Select/enter SLURM or PBS account:\n',) g0620
? ('Enter SLURM or PBS partition: (If desired; can leave blank.)\n',)
```

Maybe this is just how things look for this type of question?
