### ISSUE TITLE
Add C1120 to remap_restarts

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOS_Util#93]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/961 is looking at adding C1120 to `make_bcs`.

Once @biljanaorescanin and @bena-nasa get that working, we should also look at adding C1120 to `remap_restarts.py` as well. I believe that it would go in [remap_utils.py](https://github.com/GEOS-ESM/GEOS_Util/blob/main/pre/remap_restart/remap_utils.py).

**Comment by biljanaorescanin** [comment]
So far Bill is not reporting on any issues with TOPO or BCS files.
